import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
library.add(fas);
import 'swiper/css';
import 'swiper/css/pagination';
import ChakraProvider from './chakraUi'
import { Toaster } from 'react-hot-toast';


import Layout2 from './layout2';


export const metadata = {
  title: 'Aidrop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position='bottom-center'
        />
        <ChakraProvider>
          <Layout2>
            {children}
          </Layout2>
        </ChakraProvider>
      </body>
    </html>
  )
}
